"use strict";

const URI_LIST = [
  "vscode://schemas/argv",
  "vscode://schemas/color-theme",
  "vscode://schemas/extensions",
  "vscode://schemas/global-snippets",
  "vscode://schemas/icon-theme",
  "vscode://schemas/icons",
  "vscode://schemas/ignoredSettings",
  "vscode://schemas/keybindings",
  "vscode://schemas/language-configuration",
  "vscode://schemas/launch",
  "vscode://schemas/notebook/cellmetadata",
  "vscode://schemas/product-icon-theme",
  "vscode://schemas/settings/configurationDefaults",
  "vscode://schemas/settings/default",
  "vscode://schemas/settings/folder",
  "vscode://schemas/settings/machine",
  "vscode://schemas/settings/profile",
  "vscode://schemas/settings/resourceLanguage",
  "vscode://schemas/settings/user",
  "vscode://schemas/settings/workspace",
  "vscode://schemas/snippets",
  "vscode://schemas/tasks",
  "vscode://schemas/textmate-colors",
  "vscode://schemas/token-styling",
  "vscode://schemas/vscode-extensions",
  "vscode://schemas/vscode-product",
  "vscode://schemas/workbench-colors",
  "vscode://schemas/workspaceConfig",
];
module.exports = { URI_LIST };
