name: CRON
on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
      - name: Install Packages
        run: npm install
      - name: Copy meta
        run: cp meta-data.json old-meta-data.json
      - name: Extract
        run: xvfb-run -a npm run extract
      - name: Upload Resources
        run: npm run push-to-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
