name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
  test-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Install Packages
      run: npm install
    - name: Extract
      run: xvfb-run -a npm run extract
